# Generated by Django 5.1 on 2024-08-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SomnoAIApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='condiciones_medicas',
            new_name='obra_social',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='prueba', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='nombre', max_length=150),
            preserve_default=False,
        ),
    ]
